### ISSUE TITLE
Unable to apply some style properties to Yorkie-UI component

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/yorkie-ui#105]
**What happened**:
After applying background color and border to the Yorkie-UI component, the styles are not being applied as expected. The class is being applied correctly, but upon inspecting the CSS, it seems that there is no corresponding CSS for the class.

**What you expected to happen**:
Expected the background color and border to be applied to the Yorkie-UI component.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a background color and border to a Yorkie-UI component.
2. Verify that the styles are not being applied correctly.

**Anything else we need to know?**:

![image](https://github.com/yorkie-team/yorkie-ui/assets/52884648/4cf2ea95-de3e-42e1-84bb-1e7e8be84e92)

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- Yorkie version (use `yorkie version`): ALL

**Comment by vitran12** [comment]
hi @devleejb 

Because CSS property names will be abbreviated, you can refer to this section: https://yorkie.dev/yorkie-ui/?path=/docs/config-props--docs#short-props

However, for the border, you must declare all its individual properties in full. I will check it color now.
``` jsx 
<Box maxW="sm" borderWidth="1px" borderRadius="lg" borderColor='border.default'>
Hello
</Box>
```

------------------------------------------------------
Bugs:

- [x] Color
- [x] Padding
- [x] Grid

**Comment by devleejb** [comment]
Hi, @vitran12.

Padding isn't applied too.

![image](https://github.com/yorkie-team/yorkie-ui/assets/52884648/1677f8c1-f6e9-4ca1-901c-f501c20ee6fd)

**Comment by devleejb** [comment]
In grid, 2 columns don't work.

![image](https://github.com/yorkie-team/yorkie-ui/assets/52884648/8ed380f2-de7e-4ab3-84ee-331673498754)

**Comment by hackerwins** [comment]
Currently, we are reorganizing the structure, so it would be a good to reissue later since it has been stalled.
